### ISSUE TITLE
Just have 2 questions!

### ISSUE THREAD

**Issue by cactuspeeler** [Roberto-Nessy/OoT3D_Standalone_Free_Cam#2]
1. Is there a way to Put 2 different patches in the title folder? I had a randomizer on my 3ds that uses the same filenames.
2. Do you have a patreon I can donate to because thank you so much this is amazing!!!

**Comment by Roberto-Nessy** [comment]
1. You can only have 1 ips patch active for a game at a time, however for the randomizer that's actually not an issue if you use the nightly versions as this feature is built into the rando and was only split off to a standalone version because several people asked for it
2. I'm flattered by the sentiment but I'd feel awkward taking donations for my hobby work. Just knowing that people are enjoying using it is more than enough for me

**Comment by cactuspeeler** [comment]
Okay I just thought I should ask!
Just one more quick question. Since its a hobby of yours I was wondering how hard it would be to fix links jump forward roll in oot3d?
On the N64 if link jumped from a high place while holding forward on the control stick he would roll but on the 3ds he kinda just lands. I know its a weird inquiry but I cant find anyone else that seems to have an issue with it.
